name: myapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  go_router: ^14.2.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  http: ^1.2.1
  fl_chart: ^1.1.1
  solana: ^0.31.2+1
  shared_preferences: ^2.5.3
  camera: ^0.11.2
  image_picker: ^1.2.0
  firebase_ai: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
